// Level size: 1500 x 1500
[self registerItemWithCoords:ccp(1015.91528, 763.80273) type:kItemRepair]; // repair
[self registerItemWithCoords:ccp(501.14774, 768.28278) type:kItemRepair]; // repair
[self registerPlayerStartCoords:ccp(539.93689, 891.23785) rotate:315];
[self registerPlayerStartCoords:ccp(973.61346, 887.54382) rotate:225];
[self registerPlayerStartCoords:ccp(542.45187, 629.32501) rotate:45];
[self registerPlayerStartCoords:ccp(973.78705, 628.31488) rotate:135];
[self registerPlayerStartCoords:ccp(756.60425, 636.39606) rotate:90];
// done
