// Level size: 1027 x 1492
[self registerItemWithCoords:ccp(152.14287, 235) type:kItemRepair];
[self registerItemWithCoords:ccp(223.57143, 434.2858) type:kItemRepair];
[self registerItemWithCoords:ccp(320.71432, 882.85724) type:kItemWeaponGrenade];
[self registerItemWithCoords:ccp(416.42856, 489) type:kItemWeaponFlame];
[self registerItemWithCoords:ccp(596.42859, 489) type:kItemWeaponFlame];
[self registerItemWithCoords:ccp(700, 885.71442) type:kItemWeaponGrenade];
[self registerItemWithCoords:ccp(833.57147, 532.14288) type:kItemWeaponMine];
[self registerItemWithCoords:ccp(202.85715, 988.57141) type:kItemWeaponRocket];
[self registerItemWithCoords:ccp(815.71429, 984.28571) type:kItemWeaponRocket];
[self registerItemWithCoords:ccp(255.00002, 1127.14285) type:kItemWeaponGrenade];
[self registerItemWithCoords:ccp(762.14288, 1134.28571) type:kItemWeaponGrenade];
[self registerItemWithCoords:ccp(365, 1310) type:kItemRepair];
[self registerItemWithCoords:ccp(635, 1311.42857) type:kItemRepair];
[self registerItemWithCoords:ccp(502.85715, 1332.14285) type:kItemWeaponFlame];
[self registerItemWithCoords:ccp(425, 771.42853) type:kItemRepair];
[self registerItemWithCoords:ccp(597.85712, 770.71423) type:kItemRepair];
[self registerPlayerStartCoords:ccp(866.42859, 868.57141) rotate:180];
[self registerPlayerStartCoords:ccp(800.71429, 386.4286) rotate:135];
[self registerPlayerStartCoords:ccp(511.42859, 143.5714) rotate:90];
[self registerPlayerStartCoords:ccp(104.285713, 588.57147) rotate:0];
[self registerPlayerStartCoords:ccp(404.28574, 1158.57141) rotate:0];
[self registerPlayerStartCoords:ccp(606.42859, 1155.71429) rotate:180];
// done
